version: '3.7'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-reverse-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    networks:
      - nginx-proxy-network
    restart: always
  nginx-demo-1:
    image: nginxdemos/hello:latest
    container_name: nginx-demo-1
    networks:
      - nginx-proxy-network

  nginx-demo-2:
    image: nginxdemos/hello:latest
    container_name: nginx-demo-2
    networks:
      - nginx-proxy-network



networks:
  nginx-proxy-network:
